# Generated by Django 5.0.1 on 2024-01-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
