# Generated by Django 5.0.1 on 2024-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(default='I am sorry. I dont understand your question'),
        ),
    ]
