# Generated by Django 5.0.1 on 2024-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chat_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
