# Generated by Django 5.0.1 on 2024-02-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='chatbot.chat'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='score',
            field=models.FloatField(),
        ),
    ]
