# Generated by Django 5.0.1 on 2024-02-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_sentiment_chat_alter_sentiment_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
