# Generated by Django 5.0.1 on 2024-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_delete_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
