# Generated by Django 5.0.1 on 2024-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
