# Generated by Django 5.0.1 on 2024-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_chat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='classfication',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
