# Generated by Django 5.0.1 on 2024-02-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chat_classfication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='classfication',
            new_name='classification',
        ),
    ]
