# Generated by Django 5.0.1 on 2024-02-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
