# Generated by Django 5.0.1 on 2024-03-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Education', 'Education'), ('Security', 'Security'), ('Public Service', 'Public Service'), ('Sanitation', 'Sanitation'), ('Environment', 'Environment'), ('Health', 'Health'), ('Services', 'Services'), ('Housing', 'Housing'), ('Infractructure', 'Infractructure'), ('Jobs', 'Jobs'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
